name: Lint and build the npm package

on:
  pull_request:
    paths-ignore:
      - README.*

  push:
    branches:
      - master
    paths-ignore:
      - README.*

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  npm:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run eslint
        run: npm run eslint

      - name: Build the package
        run: npm run build

      - name: Check if there is no change
        run: |
          git add dist \
          && git diff-index --cached --exit-code HEAD -- dist
